### ISSUE TITLE
Milestone 2 feedback #2

### ISSUE THREAD

**Issue by andytai7** [UBC-MDS/encoderPy#60]
Python and R repo: 
Great
Python code: 
Code ran smoothly other than: 
Oneshot.encoder, and had this error “return [train_processed, test_processed]”

Python Tests: 
All ran smoothly 

Rcode:
Code works fine

R Tests:
Error in tests because of dependencies. Should be fine with poetry and continuous integration. 
I added this to 
install.packages("testthat")
library(testthat)
Also had to adjust where the CSV file was. 

Conjugate encoder as well as target encoder seemed to work. 
Test that for onehotencoder was really simple.

**Comment by braydentang1** [comment]
Thank you Andy. We have implemented all of these changes as you have suggested. We have also improved the tests for onehot_encoder (the function was still being built due to Robet's personal commitments).

For the R repo, it would appear that testthat is highly sensitive to where we place the data .csv file. After experimenting, the .csv file appears to be in the right place (and check() passes).
